## 00. PyTorch Fundamentals
Resource Notebook:
If you have a question:

In [41]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tesors

### Creating Tensors

PyTorch tensors are creating using torch.tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [42]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [43]:
# no dimensions
scalar.ndim

0

In [44]:
# Get tensor back as python int
scalar.item()

7

In [45]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [46]:
# number of square bracket is dimension
vector.ndim

1

In [47]:
# number of columns
vector.shape

torch.Size([2])

In [48]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [49]:
# number of dimensions (rows)
MATRIX.ndim

2

In [50]:
# number of rows, columns
MATRIX.shape

torch.Size([2, 2])

In [51]:
MATRIX[0]

tensor([7, 8])

In [52]:
MATRIX[1]

tensor([ 9, 10])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [53]:
TENSOR[0][0]

tensor([1, 2, 3])

In [54]:
TENSOR.ndim

3

In [55]:
TENSOR.shape
# 1 3 by 3 Tensor

torch.Size([1, 3, 3])

In [56]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [31]:
TENSOR_ONE = torch.tensor([[1,2,3],
                           [4,5,6]])
TENSOR_ONE

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
TENSOR_ONE.ndim

2

In [33]:
TENSOR_ONE.shape

torch.Size([2, 3])

In [35]:
TENSOR_TWO = torch.tensor([[[1,2,3],
                           [4,5,6]]])
TENSOR_TWO

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [36]:
TENSOR_TWO.ndim

3

In [37]:
TENSOR_TWO.shape

torch.Size([1, 2, 3])

### tensor.ndim
Tells us how many dimensions it is, or number of brackets

###tensor.shape
Tells us the dimensions of it, so it could be rows, columns, but also how deep each item is. It can also tell us how many layers there are and number of elements in each layer, last two will by rows then columns.


### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors: https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [68]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3219, 0.9401, 0.3371, 0.0264],
        [0.1779, 0.0726, 0.6283, 0.4098],
        [0.3086, 0.5776, 0.3614, 0.0462]])

In [69]:
random_tensor.ndim

2

In [70]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [71]:
random_tensor_chall = torch.rand(4, 5)
random_tensor_chall

tensor([[0.6884, 0.2890, 0.1974, 0.5730, 0.6287],
        [0.3392, 0.8656, 0.9516, 0.5555, 0.0886],
        [0.3831, 0.7261, 0.2068, 0.5688, 0.8886],
        [0.6308, 0.6999, 0.2014, 0.7472, 0.6178]])

In [72]:
random_tensor_chall.ndim

2

In [73]:
random_tensor_chall_two = torch.rand(1,1,2,3)
random_tensor_chall_two

tensor([[[[0.6989, 0.1645, 0.9577],
          [0.3207, 0.8938, 0.6756]]]])

In [75]:
random_tensor_chall_two.ndim, random_tensor_chall_two.shape

(4, torch.Size([1, 1, 2, 3]))

## Zeros and Ones

In [76]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [80]:
ones.dtype

torch.float32

In [81]:
random_tensor.dtype

torch.float32

In [83]:
zeros_test = torch.zeros(size=(5,2))
zeros_test

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [85]:
ones_test = torch.ones(size=(2, 5, 5))
ones_test

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])