<a href="https://colab.research.google.com/github/sifulsidd/pytorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource Notebook:
If you have a question:

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tesors

### Creating Tensors

PyTorch tensors are creating using torch.tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# no dimensions
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# number of square bracket is dimension
vector.ndim

1

In [11]:
# number of columns
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
# number of dimensions (rows)
MATRIX.ndim

2

In [24]:
# number of rows, columns
MATRIX.shape

torch.Size([2, 2])

In [16]:
MATRIX[0]

tensor([7, 8])

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [26]:
TENSOR[0][0]

tensor([1, 2, 3])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape
# 1 3 by 3 Tensor

torch.Size([1, 3, 3])

In [30]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [31]:
TENSOR_ONE = torch.tensor([[1,2,3],
                           [4,5,6]])
TENSOR_ONE

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
TENSOR_ONE.ndim

2

In [33]:
TENSOR_ONE.shape

torch.Size([2, 3])

In [35]:
TENSOR_TWO = torch.tensor([[[1,2,3],
                           [4,5,6]]])
TENSOR_TWO

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [36]:
TENSOR_TWO.ndim

3

In [37]:
TENSOR_TWO.shape

torch.Size([1, 2, 3])

### tensor.ndim
Tells us how many dimensions it is, or number of brackets

###tensor.shape
Tells us the dimensions of it, so it could be rows, columns, but also how deep each item is. It can also tell us how many layers there are and number of elements in each layer, last two will by rows then columns.
