<a href="https://colab.research.google.com/github/sifulsidd/pytorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource Notebook:
If you have a question:

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tesors

### Creating Tensors

PyTorch tensors are creating using torch.tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# no dimensions
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# number of square bracket is dimension
vector.ndim

1

In [7]:
# number of columns
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# number of dimensions (rows)
MATRIX.ndim

2

In [10]:
# number of rows, columns
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [14]:
TENSOR[0][0]

tensor([1, 2, 3])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape
# 1 3 by 3 Tensor

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [18]:
TENSOR_ONE = torch.tensor([[1,2,3],
                           [4,5,6]])
TENSOR_ONE

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
TENSOR_ONE.ndim

2

In [20]:
TENSOR_ONE.shape

torch.Size([2, 3])

In [21]:
TENSOR_TWO = torch.tensor([[[1,2,3],
                           [4,5,6]]])
TENSOR_TWO

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [22]:
TENSOR_TWO.ndim

3

In [23]:
TENSOR_TWO.shape

torch.Size([1, 2, 3])

### tensor.ndim
Tells us how many dimensions it is, or number of brackets

###tensor.shape
Tells us the dimensions of it, so it could be rows, columns, but also how deep each item is. It can also tell us how many layers there are and number of elements in each layer, last two will by rows then columns.


### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors: https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [24]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9707, 0.7042, 0.6681, 0.6485],
        [0.2440, 0.5007, 0.4127, 0.0415],
        [0.9426, 0.5661, 0.2152, 0.4276]])

In [25]:
random_tensor.ndim

2

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
random_tensor_chall = torch.rand(4, 5)
random_tensor_chall

tensor([[0.7264, 0.0119, 0.0760, 0.6725, 0.6673],
        [0.3110, 0.8115, 0.0612, 0.5426, 0.8111],
        [0.8103, 0.1527, 0.4029, 0.0893, 0.6965],
        [0.3275, 0.2528, 0.4380, 0.3797, 0.6615]])

In [28]:
random_tensor_chall.ndim

2

In [29]:
random_tensor_chall_two = torch.rand(1,1,2,3)
random_tensor_chall_two

tensor([[[[0.5493, 0.1163, 0.5474],
          [0.4821, 0.4064, 0.1378]]]])

In [30]:
random_tensor_chall_two.ndim, random_tensor_chall_two.shape

(4, torch.Size([1, 1, 2, 3]))

## Zeros and Ones

In [31]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
random_tensor.dtype

torch.float32

In [36]:
zeros_test = torch.zeros(size=(5,2))
zeros_test

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [37]:
ones_test = torch.ones(size=(2, 5, 5))
ones_test

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

### Create a range of tensors and tensors-like


In [38]:
# Use torch.arange() to create range of tensors with a start, end and a step
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [41]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the is the tensor (float32, float16, etc.), can calculate faster on numbers that take less memory, but more precision can increase bits
                               device=None, # default is cpu, if we try operations not on same device, PyTorch error
                               requires_grad=False) # if you want PyTorch to track gradients when it goes through certain numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [42]:
# Default datatype is float32
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [44]:
MATRIXTHREEBYONE = torch.tensor([3.0, 5.0, 6.0])

In [45]:
MATRIXONEBYONE = torch.tensor([2.0])

In [46]:
res = MATRIXTHREEBYONE * MATRIXONEBYONE
res

tensor([ 6., 10., 12.])

In [47]:
res.ndim, res.shape

(1, torch.Size([3]))

In [48]:
float_16_tensor_two = res.type(torch.float16)
float_16_tensor_two

tensor([ 6., 10., 12.], dtype=torch.float16)

In [49]:
multiply = float_16_tensor * float_32_tensor
multiply.dtype

torch.float32

In [50]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [51]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor, use tensor.shape

3.Tensors not on the right device - to get device from tensor, can use tensor.device

In [52]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6237, 0.4565, 0.3685, 0.5399],
        [0.4898, 0.8483, 0.2478, 0.2063],
        [0.1712, 0.3988, 0.9729, 0.0722]])

In [53]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [54]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}" )
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6237, 0.4565, 0.3685, 0.5399],
        [0.4898, 0.8483, 0.2478, 0.2063],
        [0.1712, 0.3988, 0.9729, 0.0722]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [55]:
chall_tensor = torch.rand(5, 5, dtype=torch.float16, device= None)
chall_tensor

tensor([[0.9355, 0.5884, 0.9453, 0.2485, 0.1978],
        [0.1221, 0.6514, 0.7983, 0.7021, 0.9316],
        [0.4458, 0.9414, 0.5259, 0.5684, 0.7144],
        [0.1255, 0.1040, 0.4600, 0.9038, 0.0649],
        [0.7847, 0.5781, 0.2808, 0.5562, 0.2441]], dtype=torch.float16)

In [56]:
print(chall_tensor)
print(f"Datatype of tensor: {chall_tensor.dtype}" )
print(f"Shape of tensor: {chall_tensor.shape}")
print(f"Device tensor is on: {chall_tensor.device}")

tensor([[0.9355, 0.5884, 0.9453, 0.2485, 0.1978],
        [0.1221, 0.6514, 0.7983, 0.7021, 0.9316],
        [0.4458, 0.9414, 0.5259, 0.5684, 0.7144],
        [0.1255, 0.1040, 0.4600, 0.9038, 0.0649],
        [0.7847, 0.5781, 0.2808, 0.5562, 0.2441]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([5, 5])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [57]:
# Create a tensor, add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [58]:
# Multiple by 10
tensor * 10

tensor([10, 20, 30])

In [59]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [60]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # torch.mul -> short for tensor * 10

tensor([10, 20, 30])

In [61]:
torch.add(tensor, 10) # tensor + 10

tensor([11, 12, 13])

In [62]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. **Inner dimensrions** must match
* `(3, 2) @ (3, 2)` won't work -> **RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)**
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has shape of outer dimensions
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [63]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 10)).shape

torch.Size([10, 10])

In [64]:
# Math is fun example

MATRIX_ONE = torch.tensor([[1, 2, 3],[4, 5, 6]])
MATRIX_TWO = torch.tensor([[7, 8], [9, 10], [11, 12]])
MATRIX_ONE.size(), MATRIX_TWO.size()

(torch.Size([2, 3]), torch.Size([3, 2]))

In [65]:
MATRIX_ONE @ MATRIX_TWO, torch.matmul(MATRIX_ONE, MATRIX_TWO)

(tensor([[ 58,  64],
         [139, 154]]),
 tensor([[ 58,  64],
         [139, 154]]))

In [66]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [67]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [68]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [69]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
val


CPU times: user 993 µs, sys: 841 µs, total: 1.83 ms
Wall time: 7.8 ms


tensor(14)

In [70]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 77 µs, sys: 12 µs, total: 89 µs
Wall time: 93.7 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [71]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [72]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [76]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [77]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [79]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as before), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as before), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [81]:
tensor_C = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

tensor_D = torch.tensor([[1, 2, 3, 4]])
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 1x4)

In [82]:
print(f"Original shapes: tensor_A = {tensor_C.shape}, tensor_B = {tensor_D.shape}")
print(f"New shapes: tensor_A = {tensor_C.shape} (same shape as before), tensor_B.T = {tensor_D.T.shape}")
print(f"Multiplying: {tensor_C.shape} @ {tensor_D.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_C, tensor_D.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 4]), tensor_B = torch.Size([1, 4])
New shapes: tensor_A = torch.Size([3, 4]) (same shape as before), tensor_B.T = torch.Size([4, 1])
Multiplying: torch.Size([3, 4]) @ torch.Size([4, 1]) <- inner dimensions must match
Output:

tensor([[ 30],
        [ 70],
        [110]])

Output shape: torch.Size([3, 1])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [88]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [85]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [86]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [91]:
# Find the mean, torch.mean requires a tensor of float32 datatype to work
# torch.mean(x), x.mean() # gives us a dtype error
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # convert it and see it

(tensor(45.), tensor(45.))

In [93]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [96]:
y = torch.arange(0, 1, 0.1)
y, y.dtype

(tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
         0.9000]),
 torch.float32)

In [102]:
print(torch.min(y))
print(torch.max(y))
print(torch.mean(y)) # dtype is already float32 so we are good
print(torch.sum(y))

tensor(0.)
tensor(0.9000)
tensor(0.4500)
tensor(4.5000)


In [103]:
torch.argmin(x)

tensor(0)

In [104]:
torch.argmax(x)

tensor(9)