<a href="https://colab.research.google.com/github/sifulsidd/pytorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource Notebook:
If you have a question:

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tesors

### Creating Tensors

PyTorch tensors are creating using torch.tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# no dimensions
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# number of square bracket is dimension
vector.ndim

1

In [9]:
# number of columns
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# number of dimensions (rows)
MATRIX.ndim

2

In [12]:
# number of rows, columns
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [16]:
TENSOR[0][0]

tensor([1, 2, 3])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape
# 1 3 by 3 Tensor

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [20]:
TENSOR_ONE = torch.tensor([[1,2,3],
                           [4,5,6]])
TENSOR_ONE

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
TENSOR_ONE.ndim

2

In [22]:
TENSOR_ONE.shape

torch.Size([2, 3])

In [23]:
TENSOR_TWO = torch.tensor([[[1,2,3],
                           [4,5,6]]])
TENSOR_TWO

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [24]:
TENSOR_TWO.ndim

3

In [25]:
TENSOR_TWO.shape

torch.Size([1, 2, 3])

### tensor.ndim
Tells us how many dimensions it is, or number of brackets

###tensor.shape
Tells us the dimensions of it, so it could be rows, columns, but also how deep each item is. It can also tell us how many layers there are and number of elements in each layer, last two will by rows then columns.


### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors: https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [26]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8344, 0.2949, 0.3002, 0.1095],
        [0.9123, 0.0744, 0.2981, 0.3112],
        [0.3004, 0.7664, 0.8650, 0.4133]])

In [27]:
random_tensor.ndim

2

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
random_tensor_chall = torch.rand(4, 5)
random_tensor_chall

tensor([[0.1173, 0.4274, 0.4453, 0.0855, 0.4296],
        [0.4949, 0.7467, 0.1135, 0.2233, 0.8161],
        [0.3142, 0.7804, 0.7813, 0.3474, 0.7787],
        [0.0992, 0.7223, 0.9309, 0.3469, 0.6524]])

In [30]:
random_tensor_chall.ndim

2

In [31]:
random_tensor_chall_two = torch.rand(1,1,2,3)
random_tensor_chall_two

tensor([[[[0.2720, 0.7318, 0.7545],
          [0.7318, 0.0602, 0.8138]]]])

In [32]:
random_tensor_chall_two.ndim, random_tensor_chall_two.shape

(4, torch.Size([1, 1, 2, 3]))

## Zeros and Ones

In [33]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

In [37]:
random_tensor.dtype

torch.float32

In [38]:
zeros_test = torch.zeros(size=(5,2))
zeros_test

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [39]:
ones_test = torch.ones(size=(2, 5, 5))
ones_test

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

### Create a range of tensors and tensors-like


In [40]:
# Use torch.arange() to create range of tensors with a start, end and a step
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [43]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the is the tensor (float32, float16, etc.), can calculate faster on numbers that take less memory, but more precision can increase bits
                               device=None, # default is cpu, if we try operations not on same device, PyTorch error
                               requires_grad=False) # if you want PyTorch to track gradients when it goes through certain numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [44]:
# Default datatype is float32
float_32_tensor.dtype

torch.float32

In [45]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [49]:
MATRIXTHREEBYONE = torch.tensor([3.0, 5.0, 6.0])

In [47]:
MATRIXONEBYONE = torch.tensor([2.0])

In [51]:
res = MATRIXTHREEBYONE * MATRIXONEBYONE
res

tensor([ 6., 10., 12.])

In [54]:
res.ndim, res.shape

(1, torch.Size([3]))

In [56]:
float_16_tensor_two = res.type(torch.float16)
float_16_tensor_two

tensor([ 6., 10., 12.], dtype=torch.float16)

In [59]:
multiply = float_16_tensor * float_32_tensor
multiply.dtype

torch.float32

In [60]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [61]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor, use tensor.shape

3.Tensors not on the right device - to get device from tensor, can use tensor.device

In [62]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7920, 0.4224, 0.1472, 0.3121],
        [0.8228, 0.2884, 0.6393, 0.8823],
        [0.2516, 0.5006, 0.9670, 0.3270]])

In [63]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [64]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}" )
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7920, 0.4224, 0.1472, 0.3121],
        [0.8228, 0.2884, 0.6393, 0.8823],
        [0.2516, 0.5006, 0.9670, 0.3270]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [70]:
chall_tensor = torch.rand(5, 5, dtype=torch.float16, device= None)
chall_tensor

tensor([[0.6357, 0.0400, 0.2231, 0.1470, 0.7290],
        [0.7900, 0.4556, 0.7251, 0.2383, 0.6279],
        [0.6689, 0.5361, 0.6802, 0.4536, 0.2578],
        [0.4941, 0.3032, 0.9580, 0.8657, 0.4844],
        [0.2471, 0.8740, 0.8608, 0.7686, 0.4546]], dtype=torch.float16)

In [71]:
print(chall_tensor)
print(f"Datatype of tensor: {chall_tensor.dtype}" )
print(f"Shape of tensor: {chall_tensor.shape}")
print(f"Device tensor is on: {chall_tensor.device}")

tensor([[0.6357, 0.0400, 0.2231, 0.1470, 0.7290],
        [0.7900, 0.4556, 0.7251, 0.2383, 0.6279],
        [0.6689, 0.5361, 0.6802, 0.4536, 0.2578],
        [0.4941, 0.3032, 0.9580, 0.8657, 0.4844],
        [0.2471, 0.8740, 0.8608, 0.7686, 0.4546]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([5, 5])
Device tensor is on: cpu
