<a href="https://colab.research.google.com/github/sifulsidd/pytorch/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource Notebook:
If you have a question:

In [78]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tesors

### Creating Tensors

PyTorch tensors are creating using torch.tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [79]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [80]:
# no dimensions
scalar.ndim

0

In [81]:
# Get tensor back as python int
scalar.item()

7

In [82]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [83]:
# number of square bracket is dimension
vector.ndim

1

In [84]:
# number of columns
vector.shape

torch.Size([2])

In [85]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [86]:
# number of dimensions (rows)
MATRIX.ndim

2

In [87]:
# number of rows, columns
MATRIX.shape

torch.Size([2, 2])

In [88]:
MATRIX[0]

tensor([7, 8])

In [89]:
MATRIX[1]

tensor([ 9, 10])

In [90]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [91]:
TENSOR[0][0]

tensor([1, 2, 3])

In [92]:
TENSOR.ndim

3

In [93]:
TENSOR.shape
# 1 3 by 3 Tensor

torch.Size([1, 3, 3])

In [94]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [95]:
TENSOR_ONE = torch.tensor([[1,2,3],
                           [4,5,6]])
TENSOR_ONE

tensor([[1, 2, 3],
        [4, 5, 6]])

In [96]:
TENSOR_ONE.ndim

2

In [97]:
TENSOR_ONE.shape

torch.Size([2, 3])

In [98]:
TENSOR_TWO = torch.tensor([[[1,2,3],
                           [4,5,6]]])
TENSOR_TWO

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [99]:
TENSOR_TWO.ndim

3

In [100]:
TENSOR_TWO.shape

torch.Size([1, 2, 3])

### tensor.ndim
Tells us how many dimensions it is, or number of brackets

###tensor.shape
Tells us the dimensions of it, so it could be rows, columns, but also how deep each item is. It can also tell us how many layers there are and number of elements in each layer, last two will by rows then columns.


### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors: https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [101]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1953, 0.9218, 0.8733, 0.4035],
        [0.0884, 0.9368, 0.2222, 0.4510],
        [0.3997, 0.2751, 0.6401, 0.1525]])

In [102]:
random_tensor.ndim

2

In [103]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [104]:
random_tensor_chall = torch.rand(4, 5)
random_tensor_chall

tensor([[0.6436, 0.7072, 0.1649, 0.8372, 0.4793],
        [0.8857, 0.7207, 0.7764, 0.3052, 0.8088],
        [0.1964, 0.6326, 0.3634, 0.0067, 0.8341],
        [0.1744, 0.9066, 0.5903, 0.4232, 0.0281]])

In [105]:
random_tensor_chall.ndim

2

In [106]:
random_tensor_chall_two = torch.rand(1,1,2,3)
random_tensor_chall_two

tensor([[[[0.2600, 0.8523, 0.9078],
          [0.3109, 0.8513, 0.2742]]]])

In [107]:
random_tensor_chall_two.ndim, random_tensor_chall_two.shape

(4, torch.Size([1, 1, 2, 3]))

## Zeros and Ones

In [108]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [109]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [110]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [111]:
ones.dtype

torch.float32

In [112]:
random_tensor.dtype

torch.float32

In [113]:
zeros_test = torch.zeros(size=(5,2))
zeros_test

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [114]:
ones_test = torch.ones(size=(2, 5, 5))
ones_test

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

### Create a range of tensors and tensors-like


In [115]:
# Use torch.arange() to create range of tensors with a start, end and a step
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [118]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the is the tensor (float32, float16, etc.), can calculate faster on numbers that take less memory, but more precision can increase bits
                               device=None, # default is cpu, if we try operations not on same device, PyTorch error
                               requires_grad=False) # if you want PyTorch to track gradients when it goes through certain numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [119]:
# Default datatype is float32
float_32_tensor.dtype

torch.float32

In [120]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [121]:
MATRIXTHREEBYONE = torch.tensor([3.0, 5.0, 6.0])

In [122]:
MATRIXONEBYONE = torch.tensor([2.0])

In [123]:
res = MATRIXTHREEBYONE * MATRIXONEBYONE
res

tensor([ 6., 10., 12.])

In [124]:
res.ndim, res.shape

(1, torch.Size([3]))

In [125]:
float_16_tensor_two = res.type(torch.float16)
float_16_tensor_two

tensor([ 6., 10., 12.], dtype=torch.float16)

In [126]:
multiply = float_16_tensor * float_32_tensor
multiply.dtype

torch.float32

In [127]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [128]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor, use tensor.shape

3.Tensors not on the right device - to get device from tensor, can use tensor.device

In [129]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8693, 0.3193, 0.2376, 0.8289],
        [0.6435, 0.8843, 0.4526, 0.0702],
        [0.8013, 0.2555, 0.5454, 0.3493]])

In [130]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [131]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}" )
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8693, 0.3193, 0.2376, 0.8289],
        [0.6435, 0.8843, 0.4526, 0.0702],
        [0.8013, 0.2555, 0.5454, 0.3493]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [132]:
chall_tensor = torch.rand(5, 5, dtype=torch.float16, device= None)
chall_tensor

tensor([[0.7905, 0.2065, 0.9600, 0.1592, 0.1128],
        [0.6528, 0.8687, 0.9644, 0.6958, 0.5996],
        [0.9458, 0.9756, 0.3433, 0.3931, 0.4829],
        [0.4941, 0.8633, 0.7817, 0.1484, 0.0664],
        [0.8989, 0.6255, 0.3564, 0.6909, 0.1758]], dtype=torch.float16)

In [133]:
print(chall_tensor)
print(f"Datatype of tensor: {chall_tensor.dtype}" )
print(f"Shape of tensor: {chall_tensor.shape}")
print(f"Device tensor is on: {chall_tensor.device}")

tensor([[0.7905, 0.2065, 0.9600, 0.1592, 0.1128],
        [0.6528, 0.8687, 0.9644, 0.6958, 0.5996],
        [0.9458, 0.9756, 0.3433, 0.3931, 0.4829],
        [0.4941, 0.8633, 0.7817, 0.1484, 0.0664],
        [0.8989, 0.6255, 0.3564, 0.6909, 0.1758]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([5, 5])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [134]:
# Create a tensor, add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [135]:
# Multiple by 10
tensor * 10

tensor([10, 20, 30])

In [136]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [137]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # torch.mul -> short for tensor * 10

tensor([10, 20, 30])

In [138]:
torch.add(tensor, 10) # tensor + 10

tensor([11, 12, 13])

In [139]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. **Inner dimensrions** must match
* `(3, 2) @ (3, 2)` won't work -> **RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)**
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has shape of outer dimensions
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [140]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 10)).shape

torch.Size([10, 10])

In [141]:
# Math is fun example

MATRIX_ONE = torch.tensor([[1, 2, 3],[4, 5, 6]])
MATRIX_TWO = torch.tensor([[7, 8], [9, 10], [11, 12]])
MATRIX_ONE.size(), MATRIX_TWO.size()

(torch.Size([2, 3]), torch.Size([3, 2]))

In [142]:
MATRIX_ONE @ MATRIX_TWO, torch.matmul(MATRIX_ONE, MATRIX_TWO)

(tensor([[ 58,  64],
         [139, 154]]),
 tensor([[ 58,  64],
         [139, 154]]))

In [143]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [144]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [145]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [146]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
val


CPU times: user 300 µs, sys: 0 ns, total: 300 µs
Wall time: 309 µs


tensor(14)

In [147]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 84 µs, sys: 0 ns, total: 84 µs
Wall time: 89.4 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [148]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [149]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [150]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [151]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [152]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as before), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as before), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [153]:
tensor_C = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

tensor_D = torch.tensor([[1, 2, 3, 4]])
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 1x4)

In [154]:
print(f"Original shapes: tensor_A = {tensor_C.shape}, tensor_B = {tensor_D.shape}")
print(f"New shapes: tensor_A = {tensor_C.shape} (same shape as before), tensor_B.T = {tensor_D.T.shape}")
print(f"Multiplying: {tensor_C.shape} @ {tensor_D.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_C, tensor_D.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 4]), tensor_B = torch.Size([1, 4])
New shapes: tensor_A = torch.Size([3, 4]) (same shape as before), tensor_B.T = torch.Size([4, 1])
Multiplying: torch.Size([3, 4]) @ torch.Size([4, 1]) <- inner dimensions must match
Output:

tensor([[ 30],
        [ 70],
        [110]])

Output shape: torch.Size([3, 1])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [155]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [156]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [157]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [158]:
# Find the mean, torch.mean requires a tensor of float32 datatype to work
# torch.mean(x), x.mean() # gives us a dtype error
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # convert it and see it

(tensor(46.), tensor(46.))

In [159]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [160]:
y = torch.arange(0, 1, 0.1)
y, y.dtype

(tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
         0.9000]),
 torch.float32)

In [161]:
print(torch.min(y))
print(torch.max(y))
print(torch.mean(y)) # dtype is already float32 so we are good
print(torch.sum(y))

tensor(0.)
tensor(0.9000)
tensor(0.4500)
tensor(4.5000)


## Finding the positional min and max

In [162]:
# Find position of minimum value with argmin() -> returns index of minimum value
torch.argmin(x), x[0]

(tensor(0), tensor(1))

In [163]:
# Find position of maximum value with argmax() -> returns index of max value
torch.argmax(x), x[9]


(tensor(9), tensor(91))

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [190]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [191]:
# Add an extra dimension, reshape has to be compatible with original size
# essentially change a dimension of something, so if its a 3 by 3 -> can be a multiple of 3 * 3 (9, 1)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [192]:
# Change the view
z = x.view(1, 9)
z, z.shape, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [193]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [194]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [195]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x, x.shape)
print("_____________________________________________________________________")
y = torch.squeeze(x)
print(y, y.shape)
print("_____________________________________________________________________")
z = torch.squeeze(x, 0)
print(z, z.shape)
print("_____________________________________________________________________")
a = torch.squeeze(x, 1)
print(a, a.shape)
print("_____________________________________________________________________")
g = torch.squeeze(x, (1, 2, 3))
print(g, g.shape)
print("_____________________________________________________________________")

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) torch.Size([2, 1, 2, 1, 2])
_____________________________________________________________________
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2])
_____________________________________________________________________
tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) torch.Size([2, 1, 2, 1, 2])
_____________________________________________________________________
tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]]) torch.Size([2, 2, 1, 2])
_____________________________________________________________________
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2])
_____________________________________________________________________


In [196]:
# torch.squeeze() - removes all single dimensions from a target sensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [197]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New tensor shape: torch.Size([1, 9])


In [198]:
x = torch.randn(2, 3, 5)
print(x, x.shape)
print(torch.permute(x, (2, 0, 1)), torch.permute(x, (2,0,1)).shape)

tensor([[[-1.1160, -0.2610,  0.3410,  0.3778,  0.7478],
         [-2.1079, -1.2945,  0.1256, -2.1850, -0.2976],
         [ 0.2494, -0.2300,  0.3399, -0.1803, -0.8521]],

        [[-0.7996,  0.4637,  1.3827, -1.4435,  1.3507],
         [-1.0483,  1.2615,  0.6358,  0.8750,  0.7026],
         [-1.3726, -0.0687,  1.4004,  1.0893,  0.3689]]]) torch.Size([2, 3, 5])
tensor([[[-1.1160, -2.1079,  0.2494],
         [-0.7996, -1.0483, -1.3726]],

        [[-0.2610, -1.2945, -0.2300],
         [ 0.4637,  1.2615, -0.0687]],

        [[ 0.3410,  0.1256,  0.3399],
         [ 1.3827,  0.6358,  1.4004]],

        [[ 0.3778, -2.1850, -0.1803],
         [-1.4435,  0.8750,  1.0893]],

        [[ 0.7478, -0.2976, -0.8521],
         [ 1.3507,  0.7026,  0.3689]]]) torch.Size([5, 2, 3])


In [199]:
# torch.permute - rearranges the dimensions of a target sensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels] (image data)

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (2, 0, 1)) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print(f"Previous shape: {x_original.shape}") # [height, width, color_channels]
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy


In [217]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [218]:
# Index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [219]:
# Let's index on middle bracket (dim = 1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [221]:
# Let's index on most inner bracket
x[0][2][2]

tensor(9)

In [222]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [225]:
# Get all values of 0th and 1st dimensions but only 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [232]:
# Get all values of 0 dimension but only 1 index of 1 and 2nd dimension
x[:, 1, 1]

tensor([5])

In [234]:
# Get index 0 of 0th and 1st dimension and all values of second dimension
x[0][0][:]

tensor([1, 2, 3])

In [242]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [1]:
# NumPy array to tensor
import torch
import numpy as np

# NumPy data type is float64
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy default data type of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
array.dtype

dtype('float64')

In [3]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [4]:
# Change the value of array, what will it do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
# Change tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [7]:
torch.rand(3, 3)

tensor([[0.8585, 0.3711, 0.9346],
        [0.7627, 0.5239, 0.5358],
        [0.7516, 0.6022, 0.5182]])

In [9]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2863, 0.4912, 0.3946, 0.9556],
        [0.5523, 0.3570, 0.4085, 0.3041],
        [0.4037, 0.3267, 0.1512, 0.2915]])
tensor([[0.8005, 0.1408, 0.4109, 0.8389],
        [0.1252, 0.8712, 0.6009, 0.4194],
        [0.3179, 0.7085, 0.2420, 0.1339]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [11]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed, random seed makes randomness reproducable
RANDOM_SEED = 42 # Common ones 42, 1234, 0
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Reset the random seed each time we use rand again
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
* https://docs.pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on GPUs (and making faster computations)
GPUS = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything work smoothly

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [1]:
!nvidia-smi

Mon May 12 16:25:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:

https://docs.pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count the number of devices
torch.cuda.device_count()

1